[package]
name = "corsproxy"
version = "0.1.3"
edition = "2024"
license = "MIT"
authors = ["Felix Schütt <felix.schuett@maps4print.com>"]
description = ""

[lib]
crate-type = ["cdylib", "rlib"]


[dependencies]
spin-sdk = { version = "3.1.0" }
anyhow = "1"
urlencoding = "2"
