spin_manifest_version = 2

[application]
name = "corsproxy"
version = "0.1.0"
authors = ["Felix Schütt <felix.schuett@maps4print.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "corsproxy"

[component.corsproxy]
source = "target/wasm32-wasip2/release/corsproxy.wasm"
allowed_outbound_hosts = ["https://google.com", "https://*.google.com"]
files = []

[component.corsproxy.build]
command = "cargo build --release --target wasm32-wasip2"
watch = ["src/**/*.rs", "Cargo.toml"]